// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proxy/Common.proto
#ifndef GRPC_proxy_2fCommon_2eproto__INCLUDED
#define GRPC_proxy_2fCommon_2eproto__INCLUDED

#include "proxy/Common.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace GrpcProtos {

// grpc service 函数接口使用驼峰式命名,首字母大写
// message 使用驼峰式命名,首字母大写
// message 成员数据使用下划线命名, 全小写
// enum 枚举类型使用驼峰式命名, 首字母大写
// enum 每一项使用全大写, 下划线分隔命名
//
// 统一服务接口
class UnifiedService final {
 public:
  static constexpr char const* service_full_name() {
    return "GrpcProtos.UnifiedService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest& request, ::GrpcProtos::UnifiedResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProtos::UnifiedResponse>> AsyncCallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProtos::UnifiedResponse>>(AsyncCallServiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProtos::UnifiedResponse>> PrepareAsyncCallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProtos::UnifiedResponse>>(PrepareAsyncCallServiceRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void CallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest* request, ::GrpcProtos::UnifiedResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void CallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest* request, ::GrpcProtos::UnifiedResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void CallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest* request, ::GrpcProtos::UnifiedResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProtos::UnifiedResponse>* AsyncCallServiceRaw(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProtos::UnifiedResponse>* PrepareAsyncCallServiceRaw(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status CallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest& request, ::GrpcProtos::UnifiedResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProtos::UnifiedResponse>> AsyncCallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProtos::UnifiedResponse>>(AsyncCallServiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProtos::UnifiedResponse>> PrepareAsyncCallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProtos::UnifiedResponse>>(PrepareAsyncCallServiceRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void CallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest* request, ::GrpcProtos::UnifiedResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void CallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest* request, ::GrpcProtos::UnifiedResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void CallService(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest* request, ::GrpcProtos::UnifiedResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::GrpcProtos::UnifiedResponse>* AsyncCallServiceRaw(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcProtos::UnifiedResponse>* PrepareAsyncCallServiceRaw(::grpc::ClientContext* context, const ::GrpcProtos::UnifiedRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CallService_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CallService(::grpc::ServerContext* context, const ::GrpcProtos::UnifiedRequest* request, ::GrpcProtos::UnifiedResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CallService : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CallService() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CallService() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallService(::grpc::ServerContext* /*context*/, const ::GrpcProtos::UnifiedRequest* /*request*/, ::GrpcProtos::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallService(::grpc::ServerContext* context, ::GrpcProtos::UnifiedRequest* request, ::grpc::ServerAsyncResponseWriter< ::GrpcProtos::UnifiedResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CallService<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_CallService : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_CallService() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::GrpcProtos::UnifiedRequest, ::GrpcProtos::UnifiedResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::GrpcProtos::UnifiedRequest* request, ::GrpcProtos::UnifiedResponse* response) { return this->CallService(context, request, response); }));}
    void SetMessageAllocatorFor_CallService(
        ::grpc::experimental::MessageAllocator< ::GrpcProtos::UnifiedRequest, ::GrpcProtos::UnifiedResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::GrpcProtos::UnifiedRequest, ::GrpcProtos::UnifiedResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_CallService() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallService(::grpc::ServerContext* /*context*/, const ::GrpcProtos::UnifiedRequest* /*request*/, ::GrpcProtos::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CallService(
      ::grpc::CallbackServerContext* /*context*/, const ::GrpcProtos::UnifiedRequest* /*request*/, ::GrpcProtos::UnifiedResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CallService(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::GrpcProtos::UnifiedRequest* /*request*/, ::GrpcProtos::UnifiedResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_CallService<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_CallService<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CallService : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CallService() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CallService() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallService(::grpc::ServerContext* /*context*/, const ::GrpcProtos::UnifiedRequest* /*request*/, ::GrpcProtos::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CallService : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CallService() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CallService() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallService(::grpc::ServerContext* /*context*/, const ::GrpcProtos::UnifiedRequest* /*request*/, ::GrpcProtos::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallService(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_CallService : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_CallService() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CallService(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_CallService() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallService(::grpc::ServerContext* /*context*/, const ::GrpcProtos::UnifiedRequest* /*request*/, ::GrpcProtos::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CallService(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CallService(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CallService : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CallService() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::GrpcProtos::UnifiedRequest, ::GrpcProtos::UnifiedResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::GrpcProtos::UnifiedRequest, ::GrpcProtos::UnifiedResponse>* streamer) {
                       return this->StreamedCallService(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CallService() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CallService(::grpc::ServerContext* /*context*/, const ::GrpcProtos::UnifiedRequest* /*request*/, ::GrpcProtos::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCallService(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GrpcProtos::UnifiedRequest,::GrpcProtos::UnifiedResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CallService<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CallService<Service > StreamedService;
};

}  // namespace GrpcProtos


#endif  // GRPC_proxy_2fCommon_2eproto__INCLUDED
